# Generated by Django 4.2.30 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150, verbose_name='Job Role')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', models.TextField(blank=True)),
                ('initials', models.CharField(blank=True, help_text='e.g. AB', max_length=5)),
                ('langs', models.JSONField(blank=True, default=list, verbose_name='Programming Languages')),
                ('libs', models.JSONField(blank=True, default=list, verbose_name='Libraries')),
                ('fws', models.JSONField(blank=True, default=list, verbose_name='Frameworks')),
                ('glow', models.CharField(default='glow-cyan', help_text='glow-cyan, glow-purple, glow-pink', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'created_date'],
            },
        ),
    ]
