# Generated by Django 4.2.30 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('service_type', models.CharField(max_length=150, verbose_name='Requested Service')),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('deadline', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Project Description')),
                ('pages', models.IntegerField(default=1)),
                ('estimate', models.CharField(blank=True, help_text='Total calculated price', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='new', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
