# Generated by Django 4.2.30 on 2026-07-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('vanilla', 'HTML/CSS/JS'), ('react', 'React SPA'), ('vue', 'Vue SPA'), ('angular', 'Angular SPA')], default='vanilla', max_length=20)),
                ('badge', models.CharField(blank=True, help_text='e.g. React & Tailwind', max_length=100)),
                ('client', models.CharField(blank=True, default='AetherCore Client', max_length=100)),
                ('glow', models.CharField(choices=[('glow-cyan', 'Cyan Glow'), ('glow-purple', 'Purple Glow'), ('glow-pink', 'Pink Glow')], default='glow-cyan', max_length=20)),
                ('image', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub URL')),
                ('live_url', models.URLField(blank=True, verbose_name='Live URL')),
                ('featured', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
